#!/bin/sh
# -----------------------------------------------------------------------
# Dirac run for H atom
# -----------------------------------------------------------------------

"$ADFBIN/dirac" -n 1 < "$ADFRESOURCES/Dirac/H" 
mv TAPE12 t12.rel

# -----------------------------------------------------------------------
# Create H atom
# -----------------------------------------------------------------------

cp "$ADFRESOURCES/ZORA/DZP/H" DZP-H
"$ADFBIN/start" -x "$ADFBIN/adf.3.exe" -n 1 << eor 
Create H   file=DZP-H
XC
  GGA PBE
End
relativistic ZORA
Corepotentials t12.rel
End
eor

rm DZP-H 
mv TAPE21 t21.H
rm t12.rel

# -----------------------------------------------------------------------
# Dirac run for N atom
# -----------------------------------------------------------------------

"$ADFBIN/dirac" -n 1 < "$ADFRESOURCES/Dirac/N" 
mv TAPE12 t12.rel

# -----------------------------------------------------------------------
# Create N atom
# -----------------------------------------------------------------------

cp "$ADFRESOURCES/ZORA/DZP/N" DZP-N
"$ADFBIN/start" -x "$ADFBIN/adf.3.exe" -n 1 << eor 
Create N   file=DZP-N
XC
  GGA PBE
End
relativistic ZORA
Corepotentials t12.rel
End
eor

rm DZP-N 
mv TAPE21 t21.N
rm t12.rel

# -----------------------------------------------------------------------
# Dirac run for C atom
# -----------------------------------------------------------------------

"$ADFBIN/dirac" -n 1 < "$ADFRESOURCES/Dirac/C" 
mv TAPE12 t12.rel

# -----------------------------------------------------------------------
# Create C atom
# -----------------------------------------------------------------------

cp "$ADFRESOURCES/ZORA/DZP/C" DZP-C
"$ADFBIN/start" -x "$ADFBIN/adf.3.exe" -n 1 << eor 
Create C   file=DZP-C
XC
  GGA PBE
End
relativistic ZORA
Corepotentials t12.rel
End
eor

rm DZP-C 
mv TAPE21 t21.C
rm t12.rel

# -----------------------------------------------------------------------
# Dirac run for O atom
# -----------------------------------------------------------------------

"$ADFBIN/dirac" -n 1 < "$ADFRESOURCES/Dirac/O" 
mv TAPE12 t12.rel

# -----------------------------------------------------------------------
# Create O atom
# -----------------------------------------------------------------------

cp "$ADFRESOURCES/ZORA/DZP/O" DZP-O
"$ADFBIN/start" -x "$ADFBIN/adf.3.exe" -n 1 << eor 
Create O   file=DZP-O
XC
  GGA PBE
End
relativistic ZORA
Corepotentials t12.rel
End
eor

rm DZP-O 
mv TAPE21 t21.O
rm t12.rel

# -----------------------------------------------------------------------
# Molecule
# -----------------------------------------------------------------------

"$ADFBIN/start" -x "$ADFBIN/adf.3.exe"   << eor
AnalyticalFreq
end

Geometry
end

Relativistic Scalar ZORA

SYMMETRY NOSYM

XC
  GGA PBE
end

atoms
      1         O      1.457300     -1.043800      0.268200 
      2         O      1.249200      1.116500     -0.404700 
      3         N     -1.410500      1.150700      0.182100 
      4         C     -0.708500     -0.113600      0.393700 
      5         C     -1.334500     -1.200000     -0.470200 
      6         C      0.747000      0.090300      0.030800 
      7         H     -0.766600     -0.373700      1.455800 
      8         H     -0.858000     -2.169500     -0.287800 
      9         H     -2.402300     -1.312700     -0.252100 
     10         H     -1.224800     -0.979700     -1.538400 
     11         H     -2.391600      1.042000      0.437600 
     12         H     -1.407100      1.387500     -0.809900 
     13         H      2.406200     -0.934100      0.044700 
end

Fragments
H t21.H
N t21.N
C t21.C
O t21.O
End
eor

